plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

theme: jekyll-theme-slate

title: "CS475"
description: "Computer Networks"

url                      : https://ursinusnetworks.github.io 
baseurl                  : "/Modules" 
    
formlink: https://docs.google.com/forms/d/e/1FAIpQLSfPT74-Mt3Xn2mo8FUOJ42HuiTl5ojrrGp9SVn8fzCi1NQ2dQ/formResponse?submit=Submit&usp=pp_url&entry.1751208828=magic&entry.798253037=
publickey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA9oqRTuRhmcPmYxeS1Hlr05IqmavZt/YYGupG+4FWdub/M+O5vVTP/xkYslWUEsqZAdy7kvW2h5CQRdyS7Sq321Uh4ZV+kH5vl34bcfxbirGPIxgpfhlT1NXVD+IycOd1GB2nXzMLdqp7eG709aJHIKIVKYHpQ6kuQkwhH+eM4RNSRgvxdcek6UgbiRDyikc5YA/GMEdajiJoCV2Xjm2hLLjR2dH1Hy/+7dQoL98RcXcrCkbhRK5N4BK7jUj/grfmj+lJ1rH2uTnJYfxqechji02DFGgIXnZD5PkgMezSN9Va/owlAYAzUofyqH+Lf3sUMVPs+5PZ1A7XO3G8F0RgnQIDAQAB
    -----END PUBLIC KEY-----
canvascourseid: 18044


# Reading Files
include:
  - .htaccess
  - _pages
  - files

